### ISSUE TITLE
Support for Ubuntu 19.04 Disco Dingo

### ISSUE THREAD

**Issue by martijndeb** [tuxedocomputers/tuxedo.sh#12]
Will Disco Dingo (19.04) be supported? It has some great improvements, like a newer Gnome that I adore. I've tried updating manually, but things get very crashy very quickly :(

**Comment by vinzv** [comment]
Hi there,

we only support LTS releases - sorry.
For any other questions please contact our tech support team:
https://www.tuxedocomputers.com/en/Contact.tuxedo

Thanks!
