### ISSUE TITLE
Provide Support for OpenSuse Leap 15.2

### ISSUE THREAD

**Issue by lostiniceland** [tuxedocomputers/tuxedo.sh#16]
Relese of Leap 15.2 is almost there. Repositories are available as well as Packman.

Please support this release with the appropriate repositories...the rest probably stays the same.

Thanks for this great tool.

**Comment by vinzv** [comment]
_Of course_ we'll extend this script as well as our repositories for Leap 15.2. 
But as it's planned for July 2020 there is still some time left and we're currently right in the middle of Ubuntu 20.04 preparations...
