### ISSUE TITLE
[Feature] Support for InfinityBook_S_14_v5 series

### ISSUE THREAD

**Issue by nickma82** [tuxedocomputers/tuxedo.sh#18]
First: I love the idea of the tuxedo.sh, big fan!

Could you please add support for the new [InfinityBook_S_14_v5](https://www.tuxedocomputers.com/de/Linux-Hardware/Linux-Notebooks/10-14-Zoll/TUXEDO-InfinityBook-S-14-v5.tuxedo)?

Best, Nick

**Comment by vinzv** [comment]
The InfinityBook S 14 is - as any other TUXEDO Book - fully supported by tuxedo.sh.

**Comment by nickma82** [comment]
Thanks for the quick response!

No further fixtures for the following necessary? 

-  comet lake (like the [sky-/kaby-lake](https://github.com/tuxedocomputers/tuxedo.sh/blob/master/tuxedo.sh#L130-L136))
-  product==InfinityBook_S_14_v5 [link](https://github.com/tuxedocomputers/tuxedo.sh/blob/master/tuxedo.sh#L54)
...
