### ISSUE TITLE
Add expert mode

### ISSUE THREAD

**Issue by s-hemer** [tuxedocomputers/tuxedo.sh#21]
I like the script to check for specific hardware details and install tool/driver/tweaks but please don't do that directly but suggest what to do and ask user for confirmation! Especially the software task, I personally don't want to have. Same counts for replacing the standard sources.list (the extra list in sources.list.d is fine). Therefore also stay in the console/terminal emulation where the script was called.

**Comment by vinzv** [comment]
This is a bit out of scope of this script. See the description in README.md:
> This way you can adjust you individual installation the same way we would.

So, to put it a bit more general: This script is made to adjust fresh manual installations with everything we add during factory setup.

**Comment by s-hemer** [comment]
Well, maybe. But just a little (manual) switch would allow the experienced user to choose and yet do not have to do also the rest manually (otherwise this is just usable for looking things up). And define "individual installation"... iso graphical installer, debootstrap,...?
