### ISSUE TITLE
Respect already installed Nvidia drivers

### ISSUE THREAD

**Issue by s-hemer** [tuxedocomputers/tuxedo.sh#22]
Please check differently for Nvidia drivers. I already installed `nvidia-driver-450` from Nvidia Cuda repo (https://developer.download.nvidia.com/compute/cuda/) and the script now bricked something for the GUI to come up. 
Also here, ask for confirmation as noted in #21.

**Comment by s-hemer** [comment]
To precise the "bricked something for the GUI to come up": funnily my Tuxedo now boots to a black screen (no cursor or anything) but I can login by typing the PW. Then everything runs fine including lock screen. Someone any ideas how to fix?

**Comment by vinzv** [comment]
See #21
