### ISSUE TITLE
    options i915 enable_dpcd_backlight bug

### ISSUE THREAD

**Issue by senaki** [tuxedocomputers/tuxedo.sh#24]
The line below creates a bug on Tuxedo book DX1707 that leads to a black screen after reboot :
_echo "options i915 enable_dpcd_backlight" >> /etc/modprobe.d/tuxedo-i915.conf_

The way I solve it is to pass an argument to the option _enable_dpcd_backlight_ : 

_echo "options i915 enable_dpcd_backlight=1" >> /etc/modprobe.d/tuxedo-i915.conf_

**Comment by hduelme** [comment]
You are right for Ubuntu 20.04 or Ubuntu 20.04 based systems, the syntax has changed. For me this fixed the problem, that an kernel update causes problems with the backlight control of the screen (hardware: TUXEDO InfinityBook Pro 15 v5).

I think the pull request #17  should fix the problem.

**Comment by senaki** [comment]
> You are right for Ubuntu 20.04 or Ubuntu 20.04 based systems, the syntax has changed. For me this fixed the problem, that an kernel update causes problems with the backlight control of the screen (hardware: TUXEDO InfinityBook Pro 15 v5).
> 
> I think the pull request #17 should fix the problem.

Indeed, I've forgotten to mention my Gnu Linux distribution which is Ubuntu 20.04. 
I found the issue with the same approach in request #17 . I hope it'll be taken into account soon.

**Comment by vinzv** [comment]
Thanks for the heads-up!
This is fixed via https://github.com/tuxedocomputers/tuxedo.sh/commit/f79874c5fdae705c514d7407e334f89acb3344a8.
