### ISSUE TITLE
Support ubuntu 20.10

### ISSUE THREAD

**Issue by renemadsen** [tuxedocomputers/tuxedo.sh#27]
Since we are using 20.10 in any other places, it would be good to be able to upgrade to 20.10 with full driver support.

**Comment by apoger** [comment]
Is this realized by now? Will 20.10 Ubuntu work without any limitations?

**Comment by hduelme** [comment]
If you customize the script by your own for 20.10 Ubuntu, I think it should work, but I can not guarantee.

**Comment by vinzv** [comment]
For upgrading from 20.04 to 20.10 it's not necessary to run tuxedo.sh again.
