### ISSUE TITLE
wmi driver is not working on Debian Testing (Buster) Kernel 4.13

### ISSUE THREAD

**Issue by pjaap** [tuxedocomputers/tuxedo.sh#3]
I used your driver on my Ubuntu 16.04 system and it worked fine. After Unity was discontinued, I switched to Debian Testing and cannot use Flight Mode and Keyboard LED (always on).

Any recommends?

**Comment by vinzv** [comment]
Should work, closing for now. For any questions feel free to reopen.

**Comment by pjaap** [comment]
Hi, thanks for the update. Unfortunately, I still cannot use flight mode and keyboard brightness. I tried the deb-file and the source script.
