### ISSUE TITLE
tuxedo.sh in this repo and from mytuxedo.de are out-of-sync

### ISSUE THREAD

**Issue by ombre5733** [tuxedocomputers/tuxedo.sh#5]
The tuxedo.sh script in this repo is out-of-sync with the script found at
https://mytuxedo.de/index.php/s/Pic2TDgssQal2i9/download
which is referenced e.g. from here
https://www.linux-onlineshop.de/de/Anpassungen-nach-der-Installation.tuxedo

PR #4 brings them in-sync again.

**Comment by vinzv** [comment]
Fixed
