### ISSUE TITLE
Ubuntu bionic support

### ISSUE THREAD

**Issue by SanderElias** [tuxedocomputers/tuxedo.sh#6]
When will ubuntu 18.04 be supported? I'm using the budgie variant and the airplane key doesn't work. Also it seems the intel driver isn't installed, and my CPU is stuck on high frequency.

**Comment by vinzv** [comment]
18.04 is not even released yet. Expect support by tuxedo.sh and TUXEDO Computers in general some time after the official release.

**Comment by pjaap** [comment]
Hi TUXEDO team! I am awaiting a 18.04 compatible version, too. Can you give us a time horizon when support will be added?

**Comment by vinzv** [comment]
Hi,

as 18.04 is available for TUXEDO devices since this week we're now working on updating tuxedo.sh as well. Expect it to be available within one or two weeks.

**Comment by pjaap** [comment]
Thanks! I'll do a test installation this week and run your updated script.
