### ISSUE TITLE
Tuxedo Computers site hosts newer version?!

### ISSUE THREAD

**Issue by nlenlited** [tuxedocomputers/tuxedo.sh#7]
The tuxedo computers seems to host a newer version of the .sh file; Version 3.42 instead of 3.41

**Comment by tuxedochris** [comment]
Hi nlenlited,

yes we hosted on our tuxedo homepage a different version of the tuxedo.sh. We work  on the workflow and a new version of tuxedo.sh. At the moment we work at refectroing the code, bugfixing and other things of the tuxedo.sh.
At main script is avaible under http://tuxedo.sh (You was redirect on our shop site for tuxedo.sh) and the development Version is here in GitHub. As soon we finish the tests of the devleopment version, we publish the Script on tuxedo.sh.

Cheers
Chris

**Comment by tuxedochris** [comment]
@nlenlited can we close the ticket?

**Comment by nlenlited** [comment]
> At main script is avaible under http://tuxedo.sh (You was redirect on our shop site for tuxedo.sh) and the development Version is here in GitHub. As soon we finish the tests of the devleopment version, we publish the Script on tuxedo.sh.

This where to be true if the github version would actually be newer.

**Comment by tuxedoherbert** [comment]
Hi, both pages show the same version now :)
