### ISSUE TITLE
Disable keyboard backlight by default

### ISSUE THREAD

**Issue by pjaap** [tuxedocomputers/tuxedo.sh#8]
Hi!

I am using your script for a while on a P651H machine now and is works :)

A small issue: the keyboard backlight is always on after boot and set to "blue". 

Problem: I often work with screen closed and so I do not notice that the light is on. Over the months of permanent running, the color intensity of the blue LEDs is almost completely gone. Is it possible to set the default to "off"? I went through the source code but it appears to be inside of some binary files from your servers.

Best wishes and a nice week,
patj!

**Comment by pjaap** [comment]
Forgot: I am using Ubuntu 18.04 LTS :)

**Comment by tuxedochris** [comment]
Hi Patj,

yes is possible, but not with this script. We have create a keyboard driver named "tuxedo-keyboard". You find this under https://github.com/tuxedocomputers/tuxedo-keyboard

Cheers
Chris
